[GLOBAL]
pants_version = "2.22.0"
backend_packages = [
    "pants.backend.build_files.fmt.yapf",
    "pants.backend.docker",
    "pants.backend.docker.lint.hadolint",
    "pants.backend.python",
    "pants.backend.python.lint.docformatter",
    "pants.backend.experimental.python.lint.ruff.check",
    "pants.backend.python.lint.yapf",
    "pants.backend.python.typecheck.mypy",
    "pants.backend.docker",
    "pants.backend.docker.lint.hadolint",
    "pants.backend.shell"
]
pants_ignore = [
    '.devcontainer/**',
    '.vscode/**',
    'bin/**',
    'templates/**'
]

[anonymous-telemetry]
enabled = true
repo_id = "A8B966D2-72FA-451B-965B-CACF8CF2FDC5"

[source]
root_patterns = [
    "src/*", "test/*"
]

[docker]
default_repository = "naccdata/{name}"

[python]
interpreter_constraints = ["==3.11.*"]
enable_resolves = true
resolves = { python-default = "python-default.lock"}

[python-bootstrap]
#  https://www.pantsbuild.org/docs/python-interpreter-compatibility#changing-the-interpreter-search-path.
search_path = ["<PATH>", "<PYENV>"]

[python-infer]
use_rust_parser = true

[update-build-files]
formatter = "yapf"

[environments-preview.names]
local = "//:local_linux"
local_osx = "//:local_osx"
docker = "//:docker"
